version: '3.7'
services:
  db:
    image: mariadb:latest
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: gnu
      MYSQL_USER: gnu
      MYSQL_PASSWORD: gnu2000
      MYSQL_ROOT_PASSWORD: gnu2000
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
  php:
    container_name: php
    image: 524043130808.dkr.ecr.ap-northeast-2.amazonaws.com/gnu-php
    build:
      context: images/php
    depends_on:
      - db
    ports:
      - "9000:9000"
    volumes:
      - ./source:/var/www/html
  nginx:
    container_name: nginx
    image: 524043130808.dkr.ecr.ap-northeast-2.amazonaws.com/gnu-nginx
    build:
      context: images/nginx
    volumes:
      - ./source:/var/www/html
      - ./images/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"